### PR TITLE
chore(wren-ui): remove unused code

### PR DESCRIPTION
**Pull request by fredalai**
## Description
 - Remove unused CSS styles
 - Remove unused share connection info component and the `connectionInfo` API
 - Update bootstrap and launcher since I remove the `PG_USERNAME` and `PG_PASSWORD` environments 

## docker-compose file changes
I removed the following two environments from the `.env.example` file
 - PG_USERNAME
 - PG_PASSWORD

### CODE REVIEW

**Review by andreashimin — APPROVED** [review]
LGTM for the front end parts.

**Review by onlyjackfrost — APPROVED** [review]
LGTM

**Review by paopa — APPROVED** [review]
LGTM for the AI section!

**Review by cyyeh — APPROVED** [review]
LGTM, thanks!

**Review by grieve54706 — APPROVED** [review]
LGTM. Awesome.

**Pull request merged**
