### PR TITLE
Automatic GitHub Action Contributor List

### PR DESCRIPTION
**Pull request by chilijung**
Moving PR https://github.com/Canner/WrenAI/pull/749 here. For further adjustments.

### CODE REVIEW

**Comment by chilijung** [comment]
@wwwy3y3 can you review this PR, see if we setup the GitHub action correctly.  Thanks.

**Comment by wwwy3y3** [comment]
yeah, I think it's good

**Comment by wwwy3y3** [comment]
@Ayushjhawar8 could you resolve the conflict ?

**Comment by Ayushjhawar8** [comment]
umm it says only people with write access can resolve the conflicts

**Comment by Ayushjhawar8** [comment]
im sorry but i think i messed up a bit while resolving conflicts

**Comment by Ayushjhawar8** [comment]
i think its fixed now, can you check?

**Review by wwwy3y3 — APPROVED** [review]

**Pull request merged**
