### PR TITLE
azure openai provider implementation

### PR DESCRIPTION
**Pull request by yb-sid**
- azure_openai.py : implementation of azure_openai LLM provider. Similar to openai.py , but has extra env variables.
-  .env.dev.example : update env for azure-openai models 
- .env.prod.example : update env for azure-openai models 
- change platform for wren-engine eval within wren-ai-service to amd64
- docker/.env.example : update env for azure-openai models 

Untested : Discussion WIP

### CODE REVIEW

**Review by cyyeh — COMMENTED** [review]
Great work! @yb-sid Thank you for your contribution :)

Some questions I am curious about:
- I am wondering what's the condition that api_base, api_version, and api_key are different between generator and embedding model?

**Comment by yb-sid** [comment]
@cyyeh , I'm guessing you haven't used Azure Openai Service. 
My Company has multiple instances of Azure Openai and each instance is shared by multiple teams.

Under each instance one model of chat is deployed and one model for embedding is deployed.
Having Different API_BASE and API_TOKEN allows for better tracking of costs and usage.
It also helps in tracing issues in applications as sometimes azure has outages in different regions for different model type.

**Comment by yb-sid** [comment]
https://github.com/Canner/WrenAI/blob/30746c005e80950afa8572dbd3dc8fd9b7184a4b/wren-ai-service/src/providers/document_store/qdrant.py#L202

I had to change this to 1536 for my changes to work as I do not have access to `text-embedding-3-large` model. 

Also I had to change the make commands in demo folder's makefile as per our discussion in discord

**Comment by cyyeh** [comment]
> https://github.com/Canner/WrenAI/blob/30746c005e80950afa8572dbd3dc8fd9b7184a4b/wren-ai-service/src/providers/document_store/qdrant.py#L202
> 
> I had to change this to 1536 for my changes to work as I do not have access to `text-embedding-3-large` model.
> 
> Also I had to change the make commands in demo folder's makefile as per our discussion in discord

@yb-sid these changes should be reflected in this PR: https://github.com/Canner/WrenAI/pull/376

we'll merge this PR soon

**Comment by cyyeh** [comment]
> @cyyeh , I'm guessing you haven't used Azure Openai Service. My Company has multiple instances of Azure Openai and each instance is shared by multiple teams.
> 
> Under each instance one model of chat is deployed and one model for embedding is deployed. Having Different API_BASE and API_TOKEN allows for better tracking of costs and usage. It also helps in tracing issues in applications as sometimes azure has outages in different regions for different model type.

thanks for sharing ;)

**Review by cyyeh — APPROVED** [review]
LGTM :)
Thanks for your contribution! @yb-sid

**Pull request merged**
