### PR TITLE
fix: fixed a bug for the error which was shown when waiting for response

### PR DESCRIPTION
**Pull request by sahil9001**

### CODE REVIEW

**Comment by sahil9001** [comment]
relates to #699

**Review by fredalai — COMMENTED** [review]
Thank you for your effort in addressing this bug! I noticed that the issue is not fully resolved yet. Specifically, the warning message still appears but doesn’t reflect the expected behavior.

It might be helpful to review the askProcessState-related flow.

I appreciate your continued work on this and look forward to the next iteration. Please feel free to reach out if you need any further assistance with this issue.

**Comment by sahil9001** [comment]
I was working on this, but when clicking on E-commerce data I got this error, and I can't move past the database screen.
```
{
    "errors": [
        {
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "startSampleDataset"
            ],
            "message": "The initializing SQL seems to be invalid, Please check your SQL and try again.",
            "extensions": {
                "code": "INIT_SQL_ERROR",
                "message": "The initializing SQL seems to be invalid, Please check your SQL and try again.",
                "shortMessage": "Invalid initializing SQL",
                "stacktrace": [
                    "GraphQLError: The initializing SQL seems to be invalid, Please check your SQL and try again.",
                    "    at Module.create (webpack-internal:///(api)/./src/apollo/server/utils/error.ts:89:17)",
                    "    at WrenEngineAdaptor.initDatabase (webpack-internal:///(api)/./src/apollo/server/adaptors/wrenEngineAdaptor.ts:240:68)",
                    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                    "    at async WrenEngineAdaptor.prepareDuckDB (webpack-internal:///(api)/./src/apollo/server/adaptors/wrenEngineAdaptor.ts:83:9)",
                    "    at async ProjectResolver.buildDuckDbEnvironment (webpack-internal:///(api)/./src/apollo/server/resolvers/projectResolver.ts:558:9)",
                    "    at async ProjectResolver.saveDataSource (webpack-internal:///(api)/./src/apollo/server/resolvers/projectResolver.ts:206:17)",
                    "    at async ProjectResolver.startSampleDataset (webpack-internal:///(api)/./src/apollo/server/resolvers/projectResolver.ts:119:13)"
                ]
            }
        }
    ],
    "data": null
}```

**Comment by sahil9001** [comment]
Can you please provide me exact steps to reproduce this? I don't see that banner.


https://github.com/user-attachments/assets/2811ad3d-2ed5-4ab7-ac54-b7f03553ee97

**Comment by fredalai** [comment]
> Can you please provide me exact steps to reproduce this? I don't see that banner.
> 
>  Screen.Recording.2024-10-04.at.10.46.57.AM.mov

Your steps to reproduce the problem are correct.
I saw 0:24 seconds in the video

截圖 2024-10-04 下午3 10 22

**Comment by sahil9001** [comment]
@fredalai Thanks, I got it, please check now

**Review by fredalai — APPROVED** [review]
@sahil9001  Thank you for your contribution and the effort you put into resolving the issue. Looking forward to more collaborations in the future! :D

**Comment by sahil9001** [comment]
@fredalai This is eligible for Hacktoberfest Swag, right? I can't see a form to fill

**Comment by fredalai** [comment]
Hi @sahil9001,
 
@chilijung will reply to you soon. :D

**Comment by chilijung** [comment]
Hi @sahil9001, congratulations on your amazing contribution! Please join our Discord channel https://discord.gg/Eg7VY6nYY5 and send me a direct message. I'll send you the form to fill out!

**Pull request merged**
